kind: Deployment
apiVersion: apps/v1
metadata:
  name: netflix-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-clone
  template:
    metadata:
      labels:
        app: netflix-clone
    spec:
      containers:
        - name: netflix-clone
          image: devregistry:30500/netflix-clone:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
